services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: user1
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - 9411:9411
    networks:
      - postgres

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - postgres

  config-server:
    image: kashifmajid/config-server:latest
    container_name: config-server
    ports:
      - 8080:8080
    depends_on:
      - servicereg
    networks:
      - microservice_network
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  servicereg:
    image: kashifmajid/servicereg:latest
    container_name: servicereg
    ports:
      - 8761:8761
    depends_on:
      - rabbitmq
      - zipkin
      - postgres
      - pgadmin
    networks:
      - microservice_network
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker

#  companyms:
#    image: kashifmajid/companyms:latest
#    container_name: company
#    ports:
#      - 8081:8081
#    depends_on:
#      - servicereg
#      - config-server
#    networks:
#      - microservice_network
#      - postgres
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#
#  jobms:
#    image: kashifmajid/jobms:latest
#    container_name: job
#    ports:
#      - 8082:8082
#    depends_on:
#      - servicereg
#      - config-server
#    networks:
#      - microservice_network
#      - postgres
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://servicereg:8761/eureka
#
#  reviewms:
#    image: kashifmajid/reviewms:latest
#    container_name: review
#    ports:
#      - 8083:8083
#    depends_on:
#      - servicereg
#      - config-server
#    networks:
#      - microservice_network
#      - postgres
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker

  gateway:
    image: kashifmajid/gateway:latest
    ports:
      - 8084:8084
    depends_on:
      - servicereg
    networks:
      - microservice_network
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker



networks:
  microservice_network:
    driver: bridge
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:

